- name: Execute python script to parse data files and push it to the elastic search instance
  hosts: 127.0.0.1
  connection: local
  vars:
    source: '/home/semaphore/data/to_process/'
    destination: '/home/semaphore/data/archive/{{ ansible_date_time.year }}_{{ ansible_date_time.iso8601|slice("W")|int }}/'
    api_key: "{{ lookup('ansible.builtin.env', 'ELASTIC_SEARCH_API_KEY') }}"
    api_key_id: "{{ lookup('ansible.builtin.env', 'ELASTIC_SEARCH_API_KEY_ID') }}"
  tasks:
  - name: Install specified python requirements
    ansible.builtin.pip:
      requirements: '{{playbook_dir}}/files/scripts_elasticsearch/requirements.txt'
      extra_args: --user
  - name: Creates archive directory
    file:
      path: '{{ destination }}'
      state: directory
    delegate_to: localhost
  - name: Launch python script from playbook
    ansible.builtin.script:
      cmd: scripts_elasticsearch/feed_rpi_data.py --host https://es01:9200 --json_input_folder '{{ source }}'  --api_key '{{ api_key }}' --api_key_id '{{ api_key_id }}' --json_archive_folder '{{ destination }}' -v
    args:
      executable: python3
    register: result
  - debug:
      msg: "{{ result }}"
