- name: Update noisesensor git repository and restart associated services
  hosts: rpi
  tasks:
    - name: Pull changes from noisesensor repository
      ansible.builtin.git:
        repo: https://github.com/Universite-Gustave-Eiffel/Rail4Earth.git
        dest: /home/pi/noisesensor/
        single_branch: yes
        version: main
    - name: Stop noisesensor services
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
      with_items:
        - zeroble.service
        - zerogps.service
        - zeroindicators.service
        - zerorecord.service
        - zerostorage.service
        - zerostorage_indicators.service
        - zerotrigger.service
    - name: Start noisesensor services
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        daemon_reload: true
        enabled: true
        state: started
      with_items:
        - zerogps.service
        - zerostorage.service
        - zerostorage_indicators.service
        - zerorecord.service
        - zeroindicators.service
        - zerotrigger.service
        - zeroble.service
